apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-api-server
  namespace: ray-cluster
  labels:
    app: ray-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray-api-server
  template:
    metadata:
      labels:
        app: ray-api-server
    spec:
      containers:
      - name: api-server
        image: ray-cluster-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: api
        env:
        - name: RAY_ADDRESS
          value: "ray-head-service.ray-cluster.svc.cluster.local:6379"
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ray-api-service
  namespace: ray-cluster
  labels:
    app: ray-api-server
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    name: api
    protocol: TCP
    nodePort: 30080  # Fixed nodePort for external access
  selector:
    app: ray-api-server 