apiVersion: v1
kind: PersistentVolume
metadata:
  name: ray-models-pv
  namespace: ray-cluster
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/ray-models
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ray-models-pvc
  namespace: ray-cluster
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi 