# Laptop-optimized configuration for limited resources
ray:
  head:
    port: 6379
    dashboard_port: 8265
    object_store_memory: 200000000  # Reduced to 200MB
    num_cpus: 1  # Reduced to 1 CPU
    temp_dir: /tmp/ray
    include_dashboard: true
    log_to_driver: true
    logging_level: INFO
  
  cluster:
    max_workers: 2  # Reduced for laptop
    auto_scaling: true
    min_workers: 0  # Start with no workers
    
  worker:
    head_address: ${RAY_HEAD_ADDRESS}
    port: 0
    object_store_memory: 500000000  # 500MB
    num_cpus: 2  # Reduced from 4
    num_gpus: 0  # No GPU
    temp_dir: /tmp/ray
    log_to_driver: false
    logging_level: INFO

# Load only the smallest model for testing
models:
  preload: []  # Don't preload any models for testing
  cache_dir: "/app/models"

# Resource limits for containers
resources:
  memory: 1000000000  # Reduced to 1GB
  cpu: 1  # Reduced to 1 CPU
  gpu: 0  # Head node typically doesn't need GPU

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 