#!/bin/bash

# Azure Network Security Group Configuration for Ray Cluster
# This script helps configure Azure NSG to allow Ray cluster ports

set -e

echo "🔧 Azure Network Security Group Configuration for Ray Cluster"
echo "=========================================================="

VM_PUBLIC_IP=$(curl -s ifconfig.me)
echo ""
echo "📍 Current VM Public IP: $VM_PUBLIC_IP"
echo ""

echo "📋 Required ports for Ray Cluster:"
echo "   - 6379/tcp: Ray cluster communication"
echo "   - 8265/tcp: Ray dashboard"
echo "   - 10001/tcp: Ray client (for external connections)"
echo "   - 12345/tcp: Ray object manager"
echo "   - 12346/tcp: Ray node manager"
echo ""

echo "🔧 To configure Azure NSG, you need to:"
echo ""
echo "1. Go to Azure Portal: https://portal.azure.com"
echo "2. Navigate to your VM's resource group"
echo "3. Find the Network Security Group (NSG) attached to your VM"
echo "4. Add the following inbound security rules:"
echo ""

echo "📝 Add these rules to your NSG:"
echo "--------------------------------"
echo "Rule 1:"
echo "  Name: Ray-Cluster"
echo "  Priority: 1000"
echo "  Port: 6379"
echo "  Protocol: TCP"
echo "  Source: Any"
echo "  Destination: Any"
echo "  Action: Allow"
echo ""

echo "Rule 2:"
echo "  Name: Ray-Dashboard"
echo "  Priority: 1001"
echo "  Port: 8265"
echo "  Protocol: TCP"
echo "  Source: Any"
echo "  Destination: Any"
echo "  Action: Allow"
echo ""

echo "Rule 3:"
echo "  Name: Ray-Client"
echo "  Priority: 1002"
echo "  Port: 10001"
echo "  Protocol: TCP"
echo "  Source: Any"
echo "  Destination: Any"
echo "  Action: Allow"
echo ""

echo "Rule 4:"
echo "  Name: Ray-ObjectManager"
echo "  Priority: 1003"
echo "  Port: 12345"
echo "  Protocol: TCP"
echo "  Source: Any"
echo "  Destination: Any"
echo "  Action: Allow"
echo ""

echo "Rule 5:"
echo "  Name: Ray-NodeManager"
echo "  Priority: 1004"
echo "  Port: 12346"
echo "  Protocol: TCP"
echo "  Source: Any"
echo "  Destination: Any"
echo "  Action: Allow"
echo ""

echo "🔍 Alternative: Use Azure CLI (if you have it installed):"
echo "--------------------------------------------------------"
echo ""

# Get the resource group and VM name
echo "To find your resource group and VM name, run:"
echo "  az vm list --output table"
echo ""

echo "Then add the rules with Azure CLI:"
echo "  az network nsg rule create \\"
echo "    --resource-group <your-resource-group> \\"
echo "    --nsg-name <your-nsg-name> \\"
echo "    --name Ray-Cluster \\"
echo "    --protocol tcp \\"
echo "    --priority 1000 \\"
echo "    --destination-port-range 6379 \\"
echo "    --access Allow"
echo ""

echo "🔄 After adding the NSG rules:"
echo "1. Wait 1-2 minutes for the rules to propagate"
echo "2. Test the connection from your laptop:"
echo "   telnet $VM_PUBLIC_IP 6379"
echo "   telnet $VM_PUBLIC_IP 10001"
echo ""

echo "🚀 Quick Test Commands:"
echo "From your laptop, test if ports are accessible:"
echo "  # Test Ray cluster port"
echo "  telnet $VM_PUBLIC_IP 6379"
echo "  # Test Ray client port"
echo "  telnet $VM_PUBLIC_IP 10001"
echo "  # Test Ray dashboard"
echo "  curl http://$VM_PUBLIC_IP:8265"
echo ""

echo "📊 Expected accessible services after NSG configuration:"
echo "  - Ray Dashboard: http://$VM_PUBLIC_IP:8265"
echo "  - Ray Cluster: $VM_PUBLIC_IP:6379"
echo "  - Ray Client: $VM_PUBLIC_IP:10001"
echo ""

echo "🎯 Next Steps:"
echo "1. Configure the NSG rules above"
echo "2. Test connectivity from your laptop"
echo "3. Run the worker connection script:"
echo "   ./start_remote_worker_direct.sh $VM_PUBLIC_IP"
echo ""

echo "✅ Current cluster status:"
echo "   - Head node: Running with coordinator"
echo "   - Worker nodes: 1 connected with GPT-2 actor"
echo "   - Ready for additional workers" 